[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg", "git"]

[phases.install]
cmds = [
  "echo '🚀 Installing dependencies...'",
  "pip install --break-system-packages -r requirements.txt",
  "echo '📥 Pre-downloading faster-whisper tiny model...'",
  "python -c 'from faster_whisper import WhisperModel; WhisperModel(\"tiny\", device=\"cpu\", compute_type=\"int8\")'",
  "echo '✅ faster-whisper model cached successfully'"
]

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
